### ISSUE TITLE
Toggle Not Showing inFirefox 97.0.1

### ISSUE THREAD

**Issue by CreativeCodeCat** [Joolee/userchrome-toggle#1]
![image](https://user-images.githubusercontent.com/9284733/155000386-b6e28937-cf66-41e6-a2e5-1acfc12ee9d1.png)

**Comment by Joolee** [comment]
This seems to be a display resolution thing. When I make the page smaller, the checkbox disappears like in your image. The Firefox default styling for option pages is terrible so I need to rewrite that some day. For now, I've added a min-width css option to all checkboxes, that seems to do the trick.
